#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// jo-report.mjs (test) — fixture tests for scripts/jo-report.mjs (ER-1/2/3)
//
// Covers: journey-doc parser on both generations (raw pretty-printed,
// raw single-line, compacted via doc-lib.mjs renderProgramDoc) and both
// stepJson shapes (classic array, flow-canvas {nodes}), metadata stubs and
// malformed fenced JSON (flagged, never fatal); template-doc parser against a
// doc GENERATED BY RUNNING scripts/template-doc.mjs (renderer drift breaks
// this test) incl. variants, sanitized-filename ids, and metadata-only stubs;
// the index subcommand (contract C1 shape, manifest slug/baseUrl fallback,
// cross-links, gaps, live-list overlay with liveOnly/kbOnly/statusDrift);
// and the ER-3 plumbing (RFC-4180 CSV quoting incl. pipes, report-path
// collision suffixing, mandatory caveats section, freshness line, flag
// parsing, dispatcher usage errors). Fixtures under the OS temp dir; all
// data fictional.
//
// Run:  node plugins/gs-superadmin/test/jo-report.mjs
// Zero dependencies — Node built-ins only.
// ─────────────────────────────────────────────────────────────────────────────
import { mkdirSync, rmSync, readFileSync, writeFileSync, symlinkSync, existsSync } from "node:fs";
import { join, dirname, basename, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import {
  parseJourneyDoc,
  parseTemplateDoc,
  extractFencedJson,
  buildIndex,
  parseFlags,
  renderReport,
  freshnessLine,
  mdTable,
  csvCell,
  toCsv,
  reportPath,
  emitSummary,
  writeModeReport,
  isActive,
  loadIndex,
  kbDocDisplayPath,
  resolveTokenKey,
  resolveTokensInText,
  tokenlessTemplateCount,
  tokenMetadataCaveat,
} from "../scripts/jo-report.mjs";
import { renderProgramDoc } from "../scripts/doc-lib.mjs";

const SCRIPTS = join(dirname(fileURLToPath(import.meta.url)), "..", "scripts");
const JO_REPORT = join(SCRIPTS, "jo-report.mjs");
const TEMPLATE_DOC = join(SCRIPTS, "template-doc.mjs");
const ROOT = join(tmpdir(), `gs-superadmin-jo-report-${process.pid}`);
rmSync(ROOT, { recursive: true, force: true });
mkdirSync(ROOT, { recursive: true });

let failures = 0;
function check(label, cond, detail) {
  console.log(`${cond ? "PASS" : "FAIL"}  ${label}`);
  if (!cond) {
    failures++;
    console.log(`      ${JSON.stringify(detail)?.slice(0, 400)}`);
  }
}

// ── synthetic journey payload (mirrors the observed v1.0.4 doc shape) ────────

// Classic-generation email action: the variantTokenMapping OBJECT shape,
// carrying tokenMapping.tokens[] (field + literal bindings) and
// surveyTokenMappings[] (C1 v2 step tokens[]/boundAssets[] fixtures).
// The classic-generation builders (emailAction, makeAo) and the flow-canvas
// nodes AO live in the shared reader payload corpus
// (test/fixtures/reader-payloads.mjs) — the tracer parses the same docs.
import { makeAo, JOURNEY_NODES_AO } from "./fixtures/reader-payloads.mjs";

/** @param {*} payload  @param {{id: string, name: string, pretty?: boolean, fenceBody?: string, h1?: string, fence?: boolean}} opts
 *  `h1` defaults to the name (the writer's shape); `fence: false` renders a fence-less metadata doc. */
const journeyDoc = (payload, { id, name, pretty = true, fenceBody, h1 = name, fence = true }) =>
  [
    `# ${h1}`, "",
    `> Full describe doc — generated by describe-batch.mjs, captured 2026-07-12T00:00:00.000Z.`, "",
    `- key: journey/${id}`, `- id: ${id}`, `- name: ${name}`, "",
    ...(fence ? ["```json", fenceBody ?? JSON.stringify(payload, null, pretty ? 2 : 0), "```", ""] : []),
  ].join("\n");

const ao1 = makeAo({ id: "prog-1", name: "Test Program", status: "PROCESSING", tplId: "tpl-aaa", tplName: "Welcome & Hello", variantId: "tpl-bbb" });
const payload1 = { result: true, data: { advancedOutreach: ao1 } };

function checkParsedProgram(label, entry, parseErrors) {
  check(`${label}: identity + status + model`, entry.id === "prog-1" && entry.name === "Test Program" && entry.status === "PROCESSING" && entry.statusSource === "kb" && entry.model === "DRIPV2" && entry.modelName === "Email Chain" && entry.startDate === 1670000000000 && entry.depth === "full", entry);
  check(`${label}: email step (double-stringified emailActionJson)`, entry.steps.length === 4 && entry.steps[1].emailTemplateId === "tpl-aaa" && entry.steps[1].emailTemplateName === "Welcome & Hello" && entry.steps[1].outboundAction === "SEND_EMAIL", entry.steps);
  check(`${label}: variant template ids from variantMappings`, entry.steps[1].variantTemplateIds.includes("tpl-bbb") && entry.steps[1].variantTemplateIds.includes("tpl-aaa"), entry.steps[1]);
  check(`${label}: timer step config`, entry.steps[2].timer?.timerType === "SINGLE" && entry.steps[2].timer?.timerValue === "P3D", entry.steps[2]);
  check(`${label}: schedules from aoConfiguration + source (type→scheduleType)`, entry.schedules.length === 2 && entry.schedules[0].scheduleType === "CRON" && entry.schedules[0].cronExpression === "0 0 8 1/1 * ? *" && entry.schedules[0].timeZoneName === "America/New_York" && entry.schedules[1].cronExpression === "0 0 8 ? * MON *", entry.schedules);
  check(`${label}: source mappings (standard map + custom map→array)`, entry.sources[0]?.configId === "cfg-1" && entry.sources[0]?.type === "BIONIC" && entry.sources[0]?.mappings.standard.recipientEmailAddress === "Nominee Email" && entry.sources[0]?.mappings.custom[0]?.id === "f5ewvo27" && entry.sources[0]?.mappings.custom[0]?.fieldName === "Account_ID", entry.sources);
  check(`${label}: source conditions normalized from leftOperand wrapper`, entry.sources[0]?.conditions[0]?.objectName === "nominees_obj" && entry.sources[0]?.conditions[0]?.fieldName === "OptOut" && entry.sources[0]?.conditions[0]?.fieldLabel === "Email Opt Out" && entry.sources[0]?.conditions[0]?.comparisonOperator === "EQ" && entry.sources[0]?.conditions[0]?.filterAlias === "A", entry.sources);
  // C1 v2 (classic generation): step tokens[] normalized from the
  // variantTokenMapping OBJECT shape + surveyTokenMappings → boundAssets
  const toks = entry.steps[1]?.tokens ?? [];
  const fieldTok = toks.find((t) => t.tokenKey === "embd::gs-token-first");
  check(`${label}: classic field binding normalized (label=fieldLabel, fieldName=field, objectName)`, fieldTok?.kind === "field" && fieldTok?.label === "First Name" && fieldTok?.fieldName === "firstName" && fieldTok?.objectName === "particpantscollection" && fieldTok?.fieldId === null && fieldTok?.survey === null, fieldTok);
  check(`${label}: classic literal + survey bindings normalized`, toks.find((t) => t.tokenKey === "unsubscribeText")?.kind === "literal" && toks.find((t) => t.tokenKey === "gs-token-survey")?.kind === "survey" && toks.find((t) => t.tokenKey === "gs-token-survey")?.survey?.surveyName === "Intake Survey", toks);
  check(`${label}: classic surveyTokenMappings → boundAssets SURVEY entry`, JSON.stringify(entry.steps[1]?.boundAssets) === JSON.stringify([{ type: "SURVEY", id: "SVY-1", name: "Intake Survey" }]), entry.steps[1]?.boundAssets);
  check(`${label}: C1 v2 source provenance fields verbatim`, entry.sources[0]?.participantSourceCollectionId === "coll-1" && entry.sources[0]?.participantSourceType === "BIONIC" && entry.sources[0]?.participantOperationType === "ADD_ALL_PARTICIPANT_IN_POWER_LIST", entry.sources[0]);
  check(`${label}: no parse errors`, parseErrors.length === 0, parseErrors);
}

// raw generation, pretty-printed
{
  const { entry, parseErrors } = parseJourneyDoc(journeyDoc(payload1, { id: "prog-1", name: "Test Program", pretty: true }), "kb/journey/prog-1.md");
  checkParsedProgram("journey raw pretty", entry, parseErrors);
  check("journey raw pretty: docPath recorded", entry.docPath === "kb/journey/prog-1.md", entry);
}

// raw generation, single-line fenced JSON
{
  const { entry, parseErrors } = parseJourneyDoc(journeyDoc(payload1, { id: "prog-1", name: "Test Program", pretty: false }));
  checkParsedProgram("journey raw single-line", entry, parseErrors);
}

// compacted generation — fixture generated by RUNNING doc-lib's renderer, so
// compactor drift breaks this test (requirement confirmed S1, 2026-07-12)
{
  const { doc } = renderProgramDoc({ result: true, data: { programId: "prog-1", advancedOutreach: ao1 } });
  const { entry, parseErrors } = parseJourneyDoc(doc);
  checkParsedProgram("journey compacted (renderProgramDoc)", entry, parseErrors);
}

// flow-canvas {nodes} stepJson shape (DYNAMIC_PROGRAM docs) — the
// variantTokenMapping ARRAY generation, with node-level survey identity
// (surveyIdFromEmailActionV2 + actionConfig.globalConfigInfo.surveyInfo)
{
  const nodesAo = JOURNEY_NODES_AO;
  const doc = journeyDoc({ result: true, data: { advancedOutreach: nodesAo } }, { id: "prog-nodes", name: "Flow Program" });
  const { entry, parseErrors } = parseJourneyDoc(doc);
  check("journey nodes-shape: steps mapped from nodes[]", entry.steps.length === 2 && entry.steps[0].stepType === "START" && entry.steps[1].stepId === "n2" && entry.steps[1].stepType === "SURVEY_ACTION", entry.steps);
  check("journey nodes-shape: email refs from stringified actionConfig", entry.steps[1].emailTemplateId === "tpl-nodes" && entry.steps[1].emailTemplateName === "Flow Email" && entry.steps[1].variantTemplateIds.includes("tpl-nodes"), entry.steps[1]);
  const toks = entry.steps[1].tokens;
  check("journey nodes-shape: FIELD binding normalized from the ARRAY generation", toks.find((t) => t.tokenKey === "subj::gs-flow-hris")?.kind === "field" && toks.find((t) => t.tokenKey === "subj::gs-flow-hris")?.label === "Vendor Portal Provider" && toks.find((t) => t.tokenKey === "subj::gs-flow-hris")?.fieldName === "dv1" && toks.find((t) => t.tokenKey === "subj::gs-flow-hris")?.objectName === "ao_participant_custom_fields", toks);
  check("journey nodes-shape: DYNAMIC_QUERY_V2 → kind calc with fieldId", toks.find((t) => t.tokenKey === "embd::gs-flow-calc")?.kind === "calc" && toks.find((t) => t.tokenKey === "embd::gs-flow-calc")?.fieldId === "calc-01", toks);
  check("journey nodes-shape: boundAssets from surveyInfo (agreeing v2 id adds nothing)", JSON.stringify(entry.steps[1].boundAssets) === JSON.stringify([{ type: "SURVEY", id: "SVY-FLOW", name: "Flow Intake Survey" }]), entry.steps[1].boundAssets);
  check("journey nodes-shape: identity-less SurveyToken backfilled from the step's one survey", toks.find((t) => t.tokenKey === "gs-flow-survey")?.kind === "survey" && toks.find((t) => t.tokenKey === "gs-flow-survey")?.survey?.surveyName === "Flow Intake Survey", toks);
  check("journey nodes-shape: no parse errors", parseErrors.length === 0, parseErrors);
}

// flow-canvas survey-source DISAGREEMENT: surveyIdFromEmailActionV2 differs
// from surveyInfo → both boundAssets kept (named first) + a parse-level flag
{
  const nodesAo = {
    advancedOutreachId: "prog-disagree", advancedOutreachName: "Disagree Program",
    advancedOutreachStatus: ["NEW"], advancedOutreachModel: "DYNAMIC_PROGRAM",
    stepJson: JSON.stringify({
      nodes: [{
        type: "SURVEY_ACTION", id: "n1", name: "Send", nodeType: "ACTION",
        surveyIdFromEmailActionV2: "SVY-OTHER",
        actionConfig: JSON.stringify({
          globalConfigInfo: { surveyInfo: { surveyId: "SVY-NAMED", surveyName: "Named Survey" } },
          emailTemplateId: "tpl-x", emailTemplateName: "X",
        }),
      }],
    }),
  };
  const { entry, parseErrors } = parseJourneyDoc(journeyDoc({ result: true, data: { advancedOutreach: nodesAo } }, { id: "prog-disagree", name: "Disagree Program" }));
  check("survey disagreement: both assets kept, named source first", JSON.stringify(entry.steps[0].boundAssets) === JSON.stringify([{ type: "SURVEY", id: "SVY-NAMED", name: "Named Survey" }, { type: "SURVEY", id: "SVY-OTHER", name: null }]), entry.steps[0].boundAssets);
  check("survey disagreement: flagged, never fatal", parseErrors.some((e) => /surveyIdFromEmailActionV2 'SVY-OTHER' disagrees/.test(e)), parseErrors);
}

// metadata stub, fence-less form — flagged as stub, never an error
{
  const stubDoc = ["# Stub Program", "", "- key: journey/prog-stub", "- id: prog-stub", "- name: Stub Program", ""].join("\n");
  const { entry, parseErrors } = parseJourneyDoc(stubDoc);
  check("journey stub (fence-less): depth stub, id/name from bullets, zero errors", entry.depth === "stub" && entry.id === "prog-stub" && entry.name === "Stub Program" && parseErrors.length === 0, { entry, parseErrors });
  check("journey stub (fence-less): extractFencedJson returns null", extractFencedJson(stubDoc) === null, null);
}

// metadata stub, REAL manifest.mjs `stub` output — fixture generated by
// RUNNING the stub verb, so marker/format drift breaks this test. Real stub
// docs DO carry a ```json fence (the raw list item); depth must still be
// "stub" (the S4 review confirmed fence-bearing stubs classified "full").
{
  const MANIFEST_SCRIPT = join(SCRIPTS, "manifest.mjs");
  const stubRoot = join(ROOT, "stub-verb");
  const stubJDir = join(stubRoot, "journey");
  mkdirSync(stubJDir, { recursive: true });
  const mfPath = join(stubRoot, "_manifest.json");
  const itemsPath = join(stubRoot, "plist.json");
  writeFileSync(itemsPath, JSON.stringify([
    { advancedOutreachId: "prog-real-stub", advancedOutreachName: "Real Stub Program", status: "NEW" },
  ]));
  const runManifest = (...args) => spawnSync(process.execPath, [MANIFEST_SCRIPT, ...args, "--manifest", mfPath], { encoding: "utf8" });
  const initRes = runManifest("init", "--slug", "stub-fixture", "--base-url", "https://stub-fixture.example.com", "--environment", "sandbox");
  const upsertRes = runManifest("upsert-batch", "--domain", "journey", "--file", itemsPath, "--id-field", "advancedOutreachId", "--name-field", "advancedOutreachName");
  const stubRes = runManifest("stub", "--domain", "journey", "--file", itemsPath, "--id-field", "advancedOutreachId", "--name-field", "advancedOutreachName", "--out-dir", stubJDir);
  check("journey stub (stub verb): fixture generated by manifest.mjs init/upsert-batch/stub", initRes.status === 0 && upsertRes.status === 0 && stubRes.status === 0 && JSON.parse(stubRes.stdout || "{}").stubbed === 1, { init: initRes.stderr, upsert: upsertRes.stderr, stub: stubRes.stderr, stdout: stubRes.stdout?.slice(0, 200) });
  const stubDocPath = join(stubJDir, "prog-real-stub.md");
  const realStubMd = readFileSync(stubDocPath, "utf8");
  check("journey stub (stub verb): real stub doc DOES carry a json fence", extractFencedJson(realStubMd) !== null, realStubMd.slice(0, 200));
  const { entry, parseErrors } = parseJourneyDoc(realStubMd, "journey/prog-real-stub.md");
  check("journey stub (stub verb): depth stub despite the fence, id/name kept, zero errors", entry.depth === "stub" && entry.id === "prog-real-stub" && entry.name === "Real Stub Program" && parseErrors.length === 0, { entry: { depth: entry.depth, id: entry.id, name: entry.name }, parseErrors });
  const { index: stubIdx } = buildIndex({ kbDir: stubRoot });
  check("journey stub (stub verb): index lands it in gaps.stubs", JSON.stringify(stubIdx.gaps.stubs) === JSON.stringify(["prog-real-stub"]) && stubIdx.programs["prog-real-stub"]?.depth === "stub", stubIdx.gaps);
}

// malformed fenced JSON — flagged in parseErrors, never fatal
{
  const badDoc = journeyDoc(null, { id: "prog-bad", name: "Bad Program", fenceBody: "{ not json" });
  const { entry, parseErrors } = parseJourneyDoc(badDoc);
  check("journey malformed: parseErrors flagged, id kept from bullet", parseErrors.length === 1 && /fenced JSON/.test(parseErrors[0]) && entry.id === "prog-bad" && entry.depth === "stub", { entry, parseErrors });
}

// malformed EMBEDDED layer — other layers still parse
{
  const brokenAo = { ...ao1, stepJson: "{ broken" };
  const { entry, parseErrors } = parseJourneyDoc(journeyDoc({ result: true, data: { advancedOutreach: brokenAo } }, { id: "prog-1", name: "Test Program" }));
  check("journey broken stepJson: error accumulated, schedules/sources intact", parseErrors.some((e) => /stepJson/.test(e)) && entry.steps.length === 0 && entry.schedules.length === 2 && entry.sources.length === 1, { parseErrors, entry });
}

// CRLF doc (autocrlf checkout / hand edit) — bullets and body must survive
{
  const crlfDoc = journeyDoc(payload1, { id: "prog-1", name: "Test Program" }).replace(/\n/g, "\r\n");
  const { entry, parseErrors } = parseJourneyDoc(crlfDoc);
  check("journey CRLF: ids/names clean, payload parsed", entry.id === "prog-1" && entry.name === "Test Program" && entry.depth === "full" && parseErrors.length === 0, { entry: { id: entry.id, name: entry.name, depth: entry.depth }, parseErrors });
}

// describe-batch's "(none recorded)" name sentinel never indexes as a name
{
  const noNameDoc = ["# prog-nn", "", "- key: journey/prog-nn", "- id: prog-nn", "- name: (none recorded)", ""].join("\n");
  const { entry } = parseJourneyDoc(noNameDoc);
  check("journey name sentinel: '(none recorded)' falls back to H1", entry.name === "prog-nn", entry);
}

// An EMPTY name is no name (DS-47, W8): the same rule docMeta applies to KB
// doc bullets, now on every name this parser reads — a `- name:` bullet with
// nothing after it falls back to the H1, and an empty advancedOutreachName in
// the payload keeps the doc-derived name instead of overwriting it with "".
{
  const emptyBulletDoc = journeyDoc(null, { id: "prog-e1", name: "", h1: "prog-empty-h1", fence: false });
  const { entry } = parseJourneyDoc(emptyBulletDoc);
  check("journey empty `- name:` bullet: falls back to H1 (docMeta's rule)", entry.name === "prog-empty-h1", entry);
  const emptyPayloadDoc = journeyDoc(
    { result: true, data: { advancedOutreach: { advancedOutreachId: "prog-e2", advancedOutreachName: "", advancedOutreachStatus: ["NEW"] } } },
    { id: "prog-e2", name: "Bullet Name", h1: "H1 Of Doc" }
  );
  const { entry: e2, parseErrors: pe2 } = parseJourneyDoc(emptyPayloadDoc);
  check("journey empty payload advancedOutreachName: keeps the bullet name, never \"\"", e2.name === "Bullet Name" && e2.status === "NEW" && pe2.length === 0, { name: e2.name, pe2 });
}

// ── template-doc parser (fixture generated by RUNNING template-doc.mjs) ─────

const KB = join(ROOT, "kb");
const TPL_DIR = join(KB, "journey-email-templates");
mkdirSync(TPL_DIR, { recursive: true });

const tplPayload = (emailTemplate, variants = []) => JSON.stringify({ result: true, data: { emailTemplate, variants } });
const fTplMain = join(ROOT, "tpl-main.json");
writeFileSync(fTplMain, tplPayload(
  {
    templateId: "tpl-aaa", title: "Welcome & Hello", subject: "Hi &amp; welcome ${subj::gs-token-prod}",
    plainTextContent: "Hello body with the renewal keyword inside it.",
    folderId: 68, active: true, transactional: false, variantCount: 1, builderVersion: 2,
    createdDateStr: "2023-04-14 03:04:53 UTC", createdByName: "Jordan",
    modifiedDateStr: "2023-06-12 18:26:31 UTC", modifiedByName: "Leah",
    // ER-15 (C1 v2): the CLI-synthesized flat token list + a tokenMappings
    // survey entry — the "## Tokens" fixture is GENERATED by running
    // template-doc.mjs on this payload, so renderer/parser drift breaks here
    _tokens: [
      { variant: "Default", tokenKey: "subj::gs-token-prod", displayName: "Product Name", defaultValue: "Your Product", tokenType: "STANDARD" },
      { variant: "Default", tokenKey: "gs-token-svy", displayName: null, defaultValue: null, tokenType: "SURVEY" },
    ],
    tokenMappings: { MDA: { "gs-token-svy": { surveyToken: { surveyId: "SVY-9", surveyName: "Pre-Assessment", tokenType: "SURVEY" } } } },
  },
  [{ variantName: "Variant B", subject: "V-B &amp; more", plainTextContent: "Variant body text lives here." }]
));
const fTplWeird = join(ROOT, "tpl-weird.json");
writeFileSync(fTplWeird, tplPayload({ templateId: "tpl 9/weird", title: "Weird Id", subject: "W", plainTextContent: "Weird id body content here." }));

// spawn a CLI + parse its stdout summary; shared by every spawn below
const runCli = (...args) => {
  const res = spawnSync(process.execPath, args, { encoding: "utf8" });
  let summary = null;
  try { summary = JSON.parse(res.stdout); } catch { /* asserted by callers */ }
  return { res, summary };
};

const { res: genRes, summary: genSummary } = runCli(TEMPLATE_DOC, "--out-dir", TPL_DIR, fTplMain, fTplWeird);
check("template fixture: template-doc.mjs generated 2 docs", genRes.status === 0 && genSummary?.written?.length === 2, { status: genRes.status, stderr: genRes.stderr, genSummary });
if (genSummary?.written?.length !== 2) {
  // renderer drift or spawn failure: bail with the FAIL count instead of a
  // TypeError stack trace that would hide every later check and leak ROOT
  rmSync(ROOT, { recursive: true, force: true });
  console.log(`\n${failures + 1} failure(s) — aborted: template-doc.mjs fixture generation failed`);
  process.exit(1);
}

{
  const mainPath = genSummary.written.find((w) => w.id === "tpl-aaa").path;
  const md = readFileSync(join(TPL_DIR, basename(mainPath)), "utf8");
  const { tpl, parseErrors } = parseTemplateDoc(md, "kb/journey-email-templates/x.md");
  check("template: id/title/subject (entity-decoded by renderer)", tpl.id === "tpl-aaa" && tpl.title === "Welcome & Hello" && tpl.subject === "Hi & welcome ${subj::gs-token-prod}", tpl);
  check("template: folderId numeric + active flag from combined bullet", tpl.folderId === 68 && tpl.active === true, tpl);
  check("template: body included and verbatim", tpl.bodyIncluded === true && tpl.body === "Hello body with the renewal keyword inside it.", tpl);
  check("template: variant name/subject/body", tpl.variants.length === 1 && tpl.variants[0].name === "Variant B" && tpl.variants[0].subject === "V-B & more" && tpl.variants[0].body === "Variant body text lives here.", tpl.variants);
  // ER-15: the "## Tokens" section round-trips through render + parse — the
  // C1 v2 template token shape, incl. the survey identity from tokenMappings
  check("template tokens: _tokens[] surfaced through the doc", tpl.tokens?.length === 2 && tpl.tokens[0].tokenKey === "subj::gs-token-prod" && tpl.tokens[0].displayName === "Product Name" && tpl.tokens[0].defaultValue === "Your Product" && tpl.tokens[0].variant === "Default", tpl.tokens);
  check("template tokens: survey identity joined from tokenMappings", tpl.tokens?.[1]?.tokenKey === "gs-token-svy" && tpl.tokens[1].tokenType === "SURVEY" && tpl.tokens[1].survey?.surveyId === "SVY-9" && tpl.tokens[1].survey?.surveyName === "Pre-Assessment", tpl.tokens);
  check("template: no parse errors", parseErrors.length === 0, parseErrors);
}

// a doc with NO "## Tokens" section (predates token persistence) → tokens null
{
  const weirdPath = genSummary.written.find((w) => w.id === "tpl 9/weird").path;
  const { tpl } = parseTemplateDoc(readFileSync(join(TPL_DIR, basename(weirdPath)), "utf8"));
  check("template tokens: doc without token metadata parses tokens null (predates)", tpl.tokens === null, tpl.tokens);
}

{
  const weirdPath = genSummary.written.find((w) => w.id === "tpl 9/weird").path;
  const { tpl } = parseTemplateDoc(readFileSync(join(TPL_DIR, basename(weirdPath)), "utf8"));
  check("template: id recovered verbatim from re-fetch hint despite sanitized filename", tpl.id === "tpl 9/weird", tpl);
}

{
  const stubMd = ["# Stub Template", "", "- key: journey-email-templates/tpl-stub", "- id: tpl-stub", "- name: Stub Template", ""].join("\n");
  const { tpl, parseErrors } = parseTemplateDoc(stubMd);
  check("template stub: metadata-only doc → bodyIncluded false, id from key bullet", tpl.id === "tpl-stub" && tpl.bodyIncluded === false && tpl.body === "" && tpl.variants.length === 0 && parseErrors.length === 0, { tpl, parseErrors });
}

// ── index subcommand (contract C1) ───────────────────────────────────────────

const J_DIR = join(KB, "journey");
mkdirSync(J_DIR, { recursive: true });
writeFileSync(join(J_DIR, "prog-1.md"), journeyDoc(payload1, { id: "prog-1", name: "Test Program" }));
writeFileSync(join(J_DIR, "prog-2.md"), ["# Stub Two", "", "- key: journey/prog-2", "- id: prog-2", "- name: Stub Two", ""].join("\n"));
writeFileSync(join(J_DIR, "prog-3.md"), journeyDoc(null, { id: "prog-3", name: "Broken Three", fenceBody: "{ nope" }));
const ao4 = makeAo({ id: "prog-4", name: "Paused Four", status: "PAUSE", tplId: "tpl-missing", tplName: "Missing Template" });
writeFileSync(join(J_DIR, "prog-4.md"), journeyDoc({ result: true, data: { advancedOutreach: ao4 } }, { id: "prog-4", name: "Paused Four" }));
writeFileSync(join(KB, "_manifest.json"), JSON.stringify({
  slug: "fixture-tenant",
  baseUrl: "https://fixture-tenant.example.com",
  environment: "sandbox",
  inventory: {
    "journey/prog-1": { id: "prog-1", domain: "journey", depth: "full", last_verified: "2026-07-01T00:00:00.000Z" },
    "journey/prog-4": { id: "prog-4", domain: "journey", depth: "full", last_verified: "2026-07-03T00:00:00.000Z" },
  },
}, null, 2));

const OUT1 = join(ROOT, "out", "er-index.json");
const { res: idxRes, summary: idxSummary } = runCli(JO_REPORT, "index", "--kb", KB, "--out", OUT1);
check("index: exit 0 + summary JSON on stdout", idxRes.status === 0 && idxSummary?.ok === true && idxSummary?.mode === "index", { status: idxRes.status, stderr: idxRes.stderr, stdout: idxRes.stdout?.slice(0, 300) });
check("index: counts (4 programs, 2 templates, 2 stubs, 1 parse-error doc)", idxSummary?.counts?.programs === 4 && idxSummary?.counts?.templates === 2 && idxSummary?.counts?.stubs === 2 && idxSummary?.counts?.parseErrors === 1, idxSummary?.counts);

const idx = loadIndex(OUT1);
{
  const topKeys = Object.keys(idx).sort();
  check("C1: top-level field list", JSON.stringify(topKeys) === JSON.stringify(["baseUrl", "domains", "environment", "gaps", "generatedAt", "links", "liveSweepAt", "parseErrors", "programs", "slug", "templates", "warnings"]), topKeys);
  // F-429 second pass: the index records which folders the build read and
  // why, plus the build's warnings, so a report mode built from it days later
  // can carry them (writeModeReport). Default names here — no recordings.
  check("C1: domains carries the resolved dirs + basis, warnings the build's list", idx.domains?.dirs?.journey === "journey" && idx.domains?.dirs?.templates === "journey-email-templates" && idx.domains?.basis?.journey === "default (no recording)" && Array.isArray(idx.warnings) && JSON.stringify(idx.warnings) === JSON.stringify(idxSummary?.warnings), { domains: idx.domains, warnings: idx.warnings });
  check("C1: liveSweepAt null without a live sweep", idx.liveSweepAt === null, idx.liveSweepAt);
  check("C1: slug/baseUrl/environment from manifest", idx.slug === "fixture-tenant" && idx.baseUrl === "https://fixture-tenant.example.com" && idx.environment === "sandbox", idx.slug);
  const p1 = idx.programs["prog-1"];
  const pKeys = Object.keys(p1 ?? {}).sort();
  check("C1: program entry field list", JSON.stringify(pKeys) === JSON.stringify(["depth", "docPath", "id", "lastVerified", "model", "modelName", "name", "schedules", "sources", "startDate", "status", "statusSource", "steps"]), pKeys);
  const sKeys = Object.keys(p1?.steps?.[0] ?? {}).sort();
  check("C1 v2: step entry field list (+tokens, +boundAssets)", JSON.stringify(sKeys) === JSON.stringify(["actionType", "boundAssets", "emailTemplateId", "emailTemplateName", "order", "outboundAction", "stepId", "stepName", "stepType", "timer", "tokens", "variantTemplateIds"]), sKeys);
  const tokKeys = Object.keys(p1?.steps?.[1]?.tokens?.[0] ?? {}).sort();
  check("C1 v2: step token entry field list", JSON.stringify(tokKeys) === JSON.stringify(["fieldId", "fieldName", "kind", "label", "objectName", "survey", "tokenKey"]), tokKeys);
  const schedKeys = Object.keys(p1?.schedules?.[0] ?? {}).sort();
  check("C1: schedule entry field list", JSON.stringify(schedKeys) === JSON.stringify(["cronExpression", "jobType", "lastRunSuccess", "lastSuccessTime", "nextRunTime", "runningNow", "scheduleType", "timeZoneName"]), schedKeys);
  const srcKeys = Object.keys(p1?.sources?.[0] ?? {}).sort();
  check("C1 v2: source entry field list (+3 provenance fields)", JSON.stringify(srcKeys) === JSON.stringify(["conditions", "configId", "mappings", "name", "participantOperationType", "participantSourceCollectionId", "participantSourceType", "type"]), srcKeys);
  const condKeys = Object.keys(p1?.sources?.[0]?.conditions?.[0] ?? {}).sort();
  check("C1: condition entry field list", JSON.stringify(condKeys) === JSON.stringify(["comparisonOperator", "fieldLabel", "fieldName", "filterAlias", "objectName"]), condKeys);
  const tKeys = Object.keys(idx.templates["tpl-aaa"] ?? {}).sort();
  check("C1 v2: template entry field list (+tokens)", JSON.stringify(tKeys) === JSON.stringify(["active", "body", "bodyIncluded", "docPath", "folderId", "id", "subject", "title", "tokens", "variants"]), tKeys);
  check("C1: lastVerified overlaid from manifest inventory", p1?.lastVerified === "2026-07-01T00:00:00.000Z" && idx.programs["prog-2"]?.lastVerified === null, p1?.lastVerified);
  check("C1: cross-links union of step + variant template ids", JSON.stringify(idx.links.programToTemplates["prog-1"]) === JSON.stringify(["tpl-aaa", "tpl-bbb"]) && JSON.stringify(idx.links.templateToPrograms["tpl-aaa"]) === JSON.stringify(["prog-1"]), idx.links);
  check("C1: gaps.referencedTemplatesMissing (bbb + missing, not aaa)", JSON.stringify(idx.gaps.referencedTemplatesMissing) === JSON.stringify(["tpl-bbb", "tpl-missing"]), idx.gaps.referencedTemplatesMissing);
  check("C1: gaps.stubs = stub + malformed docs", JSON.stringify(idx.gaps.stubs) === JSON.stringify(["prog-2", "prog-3"]), idx.gaps.stubs);
  check("C1: parseErrors carries doc + id + message", idx.parseErrors.length === 1 && idx.parseErrors[0].id === "prog-3" && /fenced JSON/.test(idx.parseErrors[0].errors[0]), idx.parseErrors);
  check("C1: no live-list → empty overlay gaps, statusSource kb", idx.gaps.liveOnly.length === 0 && idx.gaps.kbOnly.length === 0 && idx.gaps.statusDrift.length === 0 && p1?.statusSource === "kb", idx.gaps);
  check("freshness: KB-cached with last_verified range", freshnessLine(idx) === "statuses KB-cached; KB last_verified 2026-07-01 → 2026-07-03", freshnessLine(idx));
}

// live overlay: status drift, live-only, kb-only
const pageA = join(ROOT, "live-1.json");
const pageB = join(ROOT, "live-2.json");
writeFileSync(pageA, JSON.stringify({ result: true, data: [{ advancedOutreachId: "prog-1", advancedOutreachName: "Test Program", advancedOutreachStatus: ["PAUSE"] }] }));
writeFileSync(pageB, JSON.stringify({ result: true, data: [{ id: "prog-live-9", name: "Live Only Program", status: "NEW" }] }));
const OUT2 = join(ROOT, "out", "er-index-live.json");
const { res: liveRes } = runCli(JO_REPORT, "index", "--kb", KB, "--live-list", pageA, "--live-list", pageB, "--out", OUT2);
check("index live: exit 0", liveRes.status === 0, { status: liveRes.status, stderr: liveRes.stderr });
{
  const live = loadIndex(OUT2);
  const p1 = live.programs["prog-1"];
  check("live overlay: status overridden + statusSource live", p1?.status === "PAUSE" && p1?.statusSource === "live", p1);
  check("live overlay: statusDrift records kb vs live", live.gaps.statusDrift.length === 1 && live.gaps.statusDrift[0].id === "prog-1" && live.gaps.statusDrift[0].kbStatus === "PROCESSING" && live.gaps.statusDrift[0].liveStatus === "PAUSE", live.gaps.statusDrift);
  check("live overlay: liveOnly (in live, no KB doc)", live.gaps.liveOnly.length === 1 && live.gaps.liveOnly[0].id === "prog-live-9", live.gaps.liveOnly);
  check("live overlay: kbOnly (KB docs absent from live sweep)", live.gaps.kbOnly.map((k) => k.id).sort().join(",") === "prog-2,prog-3,prog-4", live.gaps.kbOnly);
  check("live overlay: liveSweepAt from sweep-file mtime, not build time", typeof live.liveSweepAt === "string" && freshnessLine(live) === `statuses live as of ${live.liveSweepAt}; KB last_verified 2026-07-01 → 2026-07-03`, { liveSweepAt: live.liveSweepAt, line: freshnessLine(live) });
}

// a sweep whose pages parse to zero entries must NOT flood kbOnly
{
  const pageEmpty = join(ROOT, "live-empty.json");
  writeFileSync(pageEmpty, JSON.stringify({ result: true, data: { requestId: "x", errors: [{ id: "E42", message: "boom" }] } }));
  const { index, warnings } = buildIndex({ kbDir: KB, liveListFiles: [pageEmpty] });
  check("live overlay: zero recognized entries → overlay skipped + loud warning", index.gaps.kbOnly.length === 0 && index.gaps.liveOnly.length === 0 && index.liveSweepAt === null && warnings.some((w) => /overlay skipped/.test(w)), { gaps: index.gaps.kbOnly.length, warnings });
  check("live overlay: bare-id sibling arrays (errors) never become programs", !index.gaps.liveOnly.some((e) => e.id === "E42"), index.gaps.liveOnly);
}

// live rows with an EMPTY name (DS-47, W8 + review round): "" is no name for
// the VALUE — recorded as null — but a row that spells a name key at all is
// still a program record (the admission evidence is the key, not the value,
// so an empty-named, status-less row is kept exactly as it was before ""
// became null); only a row with neither a name key nor a status is a bare-id
// sibling object. Each key spelling resolves on its own: an empty first
// spelling never hides a filled second one.
{
  const pageEmptyNames = join(ROOT, "live-empty-names.json");
  writeFileSync(pageEmptyNames, JSON.stringify({ result: true, data: [
    { advancedOutreachId: "prog-live-noname", advancedOutreachName: "", advancedOutreachStatus: ["NEW"] },
    { advancedOutreachId: "prog-live-nostatus", advancedOutreachName: "", advancedOutreachStatus: [] },
    { advancedOutreachId: "prog-live-second", advancedOutreachName: "", name: "Second Spelling", advancedOutreachStatus: [], status: "NEW" },
    { id: "bare-77" },
  ] }));
  const { index } = buildIndex({ kbDir: KB, liveListFiles: [pageEmptyNames] });
  const byId = (id) => index.gaps.liveOnly.find((e) => e.id === id);
  check("live overlay: an empty live name is recorded as null, not \"\"", byId("prog-live-noname")?.name === null && byId("prog-live-noname")?.status === "NEW", byId("prog-live-noname"));
  check("live overlay: an empty-named row with NO status is still a program (the name key is the evidence), name null", byId("prog-live-nostatus") !== undefined && byId("prog-live-nostatus").name === null && byId("prog-live-nostatus").status === null, index.gaps.liveOnly);
  check("live overlay: each key spelling resolves on its own — an empty advancedOutreachName does not hide `name`, an empty status array does not hide `status`", byId("prog-live-second")?.name === "Second Spelling" && byId("prog-live-second")?.status === "NEW", byId("prog-live-second"));
  check("live overlay: a row with neither a name key nor a status is a bare-id object, never a program", byId("bare-77") === undefined, index.gaps.liveOnly);
}

// manifest missing → dir-name slug + warning
{
  const bareKb = join(ROOT, "bare-kb");
  mkdirSync(join(bareKb, "journey"), { recursive: true });
  writeFileSync(join(bareKb, "journey", "prog-1.md"), journeyDoc(payload1, { id: "prog-1", name: "Test Program" }));
  const { index, warnings } = buildIndex({ kbDir: bareKb });
  check("manifest fallback: slug from dir name, unknowns flagged", index.slug === "bare-kb" && index.baseUrl === "unknown" && index.environment === "unknown" && warnings.some((w) => /_manifest\.json/.test(w)), { slug: index.slug, warnings });
}

// ── ER-3 plumbing ────────────────────────────────────────────────────────────

check("csv: comma field quoted", csvCell("a,b") === '"a,b"', csvCell("a,b"));
check("csv: quote doubled and quoted", csvCell('say "hi"') === '"say ""hi"""', csvCell('say "hi"'));
check("csv: newline quoted", csvCell("line1\nline2") === '"line1\nline2"', csvCell("line1\nline2"));
check("csv: pipe quoted (Gainsight names)", csvCell("ZZ|TEST|Email 3") === '"ZZ|TEST|Email 3"', csvCell("ZZ|TEST|Email 3"));
check("csv: plain field unquoted, null empty", csvCell("plain") === "plain" && csvCell(null) === "", null);
// ── wave-2 portability: junction CLI entry + BOM-tolerant index load ─────────
{
  // F-117: invoked through a junction/symlink the dispatcher must still run
  // (usage failure), never exit 0 silently. "junction" works unprivileged on
  // Windows; on POSIX the type argument is ignored.
  const linkDir = join(ROOT, "scripts-link");
  let linked = true;
  // F-137: only errors that mean "this environment cannot create links" may
  // downgrade to the skipped-PASS branch; anything else is a coding error.
  try { symlinkSync(SCRIPTS, linkDir, "junction"); }
  catch (e) { if (["EPERM", "EACCES", "ENOSYS"].includes(e?.code)) linked = false; else throw e; }
  if (linked) {
    const viaLink = spawnSync(process.execPath, [join(linkDir, "jo-report.mjs")], { encoding: "utf8" });
    check("cli-entry: junction invocation still runs main (usage, exit 1) (F-117)", viaLink.status === 1 && /usage/.test(viaLink.stderr), { status: viaLink.status, stderr: viaLink.stderr?.slice(0, 120) });
    // F-208(a): the SELF-side realpath (the F-149 half of isMainModule). Under
    // --preserve-symlinks-main the loader keeps the linked spelling in
    // import.meta.url while bare spawns realpath it anyway — so dropping only
    // the self-side realpathSync left every suite green while this exact
    // invocation silently no-opped (exit 0, no output). doc-lib is shared, so
    // one suite pinning it covers every consumer.
    const viaLinkPreserve = spawnSync(process.execPath, ["--preserve-symlinks-main", join(linkDir, "jo-report.mjs")], { encoding: "utf8" });
    check("cli-entry: junction invocation still runs main under --preserve-symlinks-main (F-208)", viaLinkPreserve.status === 1 && /usage/.test(viaLinkPreserve.stderr), { status: viaLinkPreserve.status, stderr: viaLinkPreserve.stderr?.slice(0, 120) });
  } else {
    check("cli-entry: junction invocation still runs main (F-117) [link creation unavailable — skipped]", true, null);
    check("cli-entry: junction invocation still runs main under --preserve-symlinks-main (F-208) [link creation unavailable — skipped]", true, null);
  }
}
{
  // F-118/F-130: loadIndex tolerates a leading BOM (the strip is now the
  // shared escape-spelled stripBom, not a raw invisible literal). BOM via
  // fromCharCode — never a literal in this file (F-130 rule).
  const bomIndexPath = join(ROOT, "bom-index.json");
  writeFileSync(bomIndexPath, String.fromCharCode(0xfeff) + JSON.stringify({ programs: {}, templates: {} }));
  let loaded = null;
  try { loaded = loadIndex(bomIndexPath); } catch { /* asserted below */ }
  check("loadIndex: BOM-prefixed index parses (F-118)", loaded !== null && typeof loaded.programs === "object", loaded);
}

// The leading U+FEFF is the deliberate Excel-decoding BOM (F-124) — pinned
// here byte-for-byte so neither the BOM nor the CRLF policy can drift.
check("csv: RFC-4180 CRLF document with UTF-8 BOM", toCsv(["a", "b"], [["1", "x,y"]]) === '\uFEFF' + 'a,b\r\n1,"x,y"\r\n', JSON.stringify(toCsv(["a", "b"], [["1", "x,y"]])));
check("csv: BOM is single and leading only", (() => { const c = toCsv(["a"], [["x"]]); return c.indexOf("\uFEFF") === 0 && c.lastIndexOf("\uFEFF") === 0; })(), null);

{
  const rDir = join(ROOT, "reports-adhoc");
  mkdirSync(rDir, { recursive: true });
  const p1 = reportPath(rDir, "search", "2026-07-12");
  check("reportPath: first report gets the plain name", basename(p1) === "search-2026-07-12.md", p1);
  writeFileSync(p1, "x");
  const p2 = reportPath(rDir, "search", "2026-07-12");
  check("reportPath: collision → -2 suffix, never overwrite", basename(p2) === "search-2026-07-12-2.md", p2);
  writeFileSync(p2, "x");
  check("reportPath: second collision → -3", basename(reportPath(rDir, "search", "2026-07-12")) === "search-2026-07-12-3.md", null);

  // kbDocDisplayPath: absolute only when the path exists from cwd; a docPath
  // that doesn't resolve to a real file stays as the honest relative string.
  check(
    "kbDocDisplayPath: existing path → absolute, missing path → unchanged, empty → passthrough",
    kbDocDisplayPath(p1) === p1 /* p1 is already absolute + exists */ &&
      kbDocDisplayPath("no-such-slug/journey/nope.md") === "no-such-slug/journey/nope.md" &&
      kbDocDisplayPath(null) === null,
    kbDocDisplayPath("no-such-slug/journey/nope.md")
  );
}

{
  const md = renderReport({
    mode: "search", slug: "fixture-tenant", baseUrl: "https://fixture-tenant.example.com", environment: "sandbox",
    generatedAt: "2026-07-12T00:00:00.000Z", argsLine: "--query 'renewal'",
    freshness: "statuses KB-cached; KB last_verified 2026-07-01 → 2026-07-03",
    sections: ["## Hits\n\nnone"], caveats: [], rerun: "node jo-report.mjs search --query 'renewal'",
  });
  check("report: header block lines", md.includes("# JO report — search") && md.includes("- tenant: fixture-tenant (https://fixture-tenant.example.com, sandbox)") && md.includes("- generated: 2026-07-12T00:00:00.000Z") && md.includes("- mode: search · args: --query 'renewal'") && md.includes("- freshness: statuses KB-cached"), md.slice(0, 400));
  check("report: caveats section MANDATORY even when empty", md.includes("## Caveats & data gaps") && md.includes("_none identified this run_"), md);
  check("report: re-run footer", md.includes("Re-run: `node jo-report.mjs search --query 'renewal'`"), md);
  const md2 = renderReport({ mode: "deps", slug: "s", caveats: ["3 stubs not searched", "scope cap 619/1,336"] });
  check("report: caveats listed when present", md2.includes("- 3 stubs not searched") && md2.includes("- scope cap 619/1,336") && !md2.includes("_none identified this run_"), md2);
  // title override (tenant-deps.mjs / ER-11): H1 replaced, mode line untouched
  const md3 = renderReport({ mode: "tenant-deps", title: "Tenant-wide dependency report", slug: "s" });
  check("report: title override replaces H1 only", md3.startsWith("# Tenant-wide dependency report") && md3.includes("- mode: tenant-deps"), md3.slice(0, 120));
}

check("mdTable: pipes escaped, newlines to <br>", mdTable(["h"], [["a|b\nc"]]).includes("| a\\|b<br>c |"), mdTable(["h"], [["a|b\nc"]]));

{
  const f = parseFlags(["--kb", "k", "--live-list", "a", "--live-list", "b", "--active-only", "pos"], { repeatable: ["live-list"], boolean: ["active-only"] });
  check("flags: repeatable collects, boolean true, positional kept", JSON.stringify(f["live-list"]) === JSON.stringify(["a", "b"]) && f["active-only"] === true && f.kb === "k" && f._[0] === "pos", f);
  let threw = null;
  try { parseFlags(["--kb", "a", "--kb", "b"]); } catch (e) { threw = e.message; }
  check("flags: non-repeatable duplicate throws", /twice/.test(threw ?? ""), threw);
  let threw2 = null;
  try { parseFlags(["--out", "--live-list", "p.json"], { repeatable: ["live-list"] }); } catch (e) { threw2 = e.message; }
  check("flags: missing value never swallows the next --flag", /--out requires a value/.test(threw2 ?? ""), threw2);
  const c3 = parseFlags(["--query", "a", "--query", "b", "--include-paused"]);
  check("flags: C3 defaults — query repeats, include-paused boolean", JSON.stringify(c3.query) === JSON.stringify(["a", "b"]) && c3["include-paused"] === true, c3);
}

check("isActive: PROCESSING only by default, PAUSE via includePaused", isActive({ status: "PROCESSING" }) && !isActive({ status: "PAUSE" }) && isActive({ status: "PAUSE" }, { includePaused: true }) && !isActive({ status: "STOP" }, { includePaused: true }), null);

// ── ER-15: the shared token resolver (ruled ladder, P-2 2026-07-16) ─────────
{
  const stepTokens = [
    { tokenKey: "subj::gs-hris", kind: "field", label: "Vendor Portal Provider", objectName: "ao_participant_custom_fields", fieldName: "dv1", fieldId: null, survey: null },
    { tokenKey: "gs-svy", kind: "survey", label: null, objectName: null, fieldName: null, fieldId: null, survey: { surveyId: "SVY-1", surveyName: "Intake Survey" } },
    { tokenKey: "unsubscribeText", kind: "literal", label: null, objectName: null, fieldName: null, fieldId: null, survey: null },
    { tokenKey: "embd::gs-calc", kind: "calc", label: "CSM Name Calc", objectName: null, fieldName: null, fieldId: "f-1", survey: null },
    { tokenKey: "embd::gs-mystery", kind: "literal", label: null, objectName: null, fieldName: null, fieldId: null, survey: null },
  ];
  const templateTokens = [
    { tokenKey: "subj::gs-hris", displayName: "Product Name", defaultValue: "Your Product", tokenType: "STANDARD", variant: "Default", survey: null },
    { tokenKey: "embd::gs-author-only", displayName: "Author Label", defaultValue: null, tokenType: "STANDARD", variant: "Default", survey: null },
    // the program pins this one to a LITERAL — the author label must NOT win
    { tokenKey: "embd::gs-mystery", displayName: "Misleading Author Label", defaultValue: null, tokenType: "STANDARD", variant: "Default", survey: null },
  ];
  const ctx = { stepTokens, templateTokens };
  check("resolver: program binding WINS over the template author label", resolveTokenKey("subj::gs-hris", ctx) === "{Vendor Portal Provider}", resolveTokenKey("subj::gs-hris", ctx));
  check("resolver: template displayName is the fallback", resolveTokenKey("embd::gs-author-only", ctx) === "{Author Label}", null);
  check("resolver: SURVEY → {Survey: <name>}", resolveTokenKey("gs-svy", ctx) === "{Survey: Intake Survey}", null);
  check("resolver: unsubscribeText → {unsubscribe link}", resolveTokenKey("unsubscribeText", ctx) === "{unsubscribe link}", null);
  check("resolver: calc binding resolves by label", resolveTokenKey("embd::gs-calc", ctx) === "{CSM Name Calc}", null);
  check("resolver: system placeholders stay as-is", resolveTokenKey("%us", ctx) === null && resolveTokenKey("%s", ctx) === null, null);
  // a program-side LITERAL binding pins the token to a fixed value — it must
  // stay raw even when the template author gave the token a display name
  check("resolver: literal step binding stays raw (author label never misrepresents a pinned literal)", resolveTokenKey("embd::gs-mystery", ctx) === null && resolveTokenKey("gs-total-stranger", ctx) === null, null);
  check("resolver: gs- prefix spelling flexibility (bare key matches gs- binding)", resolveTokenKey("subj::hris", ctx) === "{Vendor Portal Provider}", null);
  const text = "Hi ${subj::gs-hris}! Survey: ${gs-svy}. Unsub ${%us}. Raw ${embd::gs-mystery}. [image::Logo] [cid:gs-x]";
  const r = resolveTokensInText(text, ctx);
  check("resolveTokensInText: inline {Label}, survey name, %us/image/cid/raw untouched", r.text === "Hi {Vendor Portal Provider}! Survey: {Survey: Intake Survey}. Unsub ${%us}. Raw ${embd::gs-mystery}. [image::Logo] [cid:gs-x]" && r.resolved === 2 && r.unresolved === 1, r);
  check("resolveTokensInText: token-free text passes through", resolveTokensInText("no tokens here", ctx).text === "no tokens here", null);
}

// tokenless-template accounting (the ER-15 backfill gap class)
{
  const ix = { templates: {
    a: { id: "a", tokens: null }, b: { id: "b", tokens: [] }, c: { id: "c", tokens: [{ tokenKey: "k" }] }, d: { id: "d" },
  } };
  check("tokenlessTemplateCount: null/absent counted, [] not", tokenlessTemplateCount(ix) === 2 && tokenlessTemplateCount(ix, new Set(["a"])) === 1 && tokenlessTemplateCount(ix, new Set(["b", "c"])) === 0, null);
  check("tokenMetadataCaveat: present when tokenless docs exist, null when none", /2 template doc\(s\) predate token metadata/.test(tokenMetadataCaveat(ix) ?? "") && tokenMetadataCaveat({ templates: { c: { id: "c", tokens: [] } } }) === null, tokenMetadataCaveat(ix));
}

{
  // emitSummary must never let an explicitly-undefined base key vanish from stdout
  const orig = console.log;
  let printed = "";
  console.log = (s) => { printed = s; };
  emitSummary({ ok: undefined, mode: "search", reportPath: "r.md" });
  console.log = orig;
  const parsed = JSON.parse(printed);
  check("emitSummary: explicit undefined ok still emits ok:true", parsed.ok === true && parsed.mode === "search" && parsed.reportPath === "r.md" && "counts" in parsed && "caveatCount" in parsed && Array.isArray(parsed.warnings), parsed);
}

{
  // a variant body line that itself starts with "- subject: " must survive
  const md = ["# T", "", "- key: journey-email-templates/tpl-v", "", "> `gs-admin --json jo email template --id tpl-v`", "", "## Body (plain text)", "", "main body", "", "## Variants", "", "### V1", "", "- subject: Real Subject", "", "body line one", "- subject: quoted metadata inside the body", "body line two", ""].join("\n");
  const { tpl } = parseTemplateDoc(md);
  check("template variant: only FIRST subject bullet is metadata; later ones stay in body", tpl.variants[0]?.subject === "Real Subject" && tpl.variants[0]?.body.includes("- subject: quoted metadata inside the body"), tpl.variants);
}

// ── writeModeReport: the mode modules' shared tail (F-362) ───────────────────
// Pinned at the definition site (the doc-lib-fixtures precedent): the four
// mode suites' byte locks prove output identity; these pin the decision
// points the locks' clean inputs never reach — the caveat scan over sections
// and caveats (the one behaviour the hoist unified: two modes used to scan
// the rerun line only), write: false, and the --csv-dir absent/present arms.
{
  // The shq rule re-derived, not imported (Class B: independent probe).
  const q = (s) => (/^[A-Za-z0-9_\-./:@]+$/.test(s) ? s : `'${s.replace(/'/g, "'\\''")}'`);
  const ESC = "'\\''"; // the bash apostrophe escape the caveat detects
  const index = { slug: "fixture-tenant", baseUrl: "https://fixture-tenant.example.com", environment: "sandbox", programs: {}, generatedAt: "2026-07-12T00:00:00.000Z" };
  const dir = join(ROOT, "wmr");
  const flags = { index: join(dir, "ix.json"), report: join(dir, "rep"), "csv-dir": join(dir, "csv") };

  // (a) the rerun line: node <dispatcher> <mode> --index … <modeArgs> --report … --csv-dir …
  const cavA = ["existing caveat"];
  const utcBefore = new Date().toISOString().slice(0, 10);
  const a = writeModeReport({ mode: "search", flags, modeArgs: ["--query zebra", "--all-terms"], sections: ["## S", "body"], caveats: cavA, index });
  const utcAfter = new Date().toISOString().slice(0, 10);
  const mdA = readFileSync(a.outPath, "utf8");
  const rerunA = mdA.split("\n").find((l) => l.startsWith("Re-run:"));
  check(
    "writeModeReport: rerun = node <dispatcher> <mode> --index … <modeArgs> --report … --csv-dir …",
    rerunA === `Re-run: \`node ${q(process.argv[1])} search --index ${q(flags.index)} --query zebra --all-terms --report ${q(flags.report)} --csv-dir ${q(flags["csv-dir"])}\``,
    rerunA
  );
  check("writeModeReport: report named <mode>-<date>.md under --report; header carries mode + args + freshness; sections and caveats rendered", /^search-\d{4}-\d{2}-\d{2}\.md$/.test(basename(a.outPath)) && dirname(a.outPath) === resolve(flags.report) && mdA.includes("- mode: search · args: --query zebra --all-terms") && mdA.includes(`- freshness: ${freshnessLine(index)}`) && mdA.includes("## S\n\nbody\n\n## Caveats") && mdA.includes("- existing caveat"), mdA.slice(0, 400));
  // F-370: every filename check above (here and in the four mode locks) tests the
  // date SHAPE, and reportPath's own unit checks all pass `date` explicitly — so the
  // DEFAULT (nowIso().slice(0,10)) was pinned by nothing: a hard-coded date passed the
  // whole battery. Pin the VALUE here. Bounded either side of the call rather than
  // compared to one `now`, so a UTC midnight rollover mid-run cannot flake it. One
  // assertion covers all four modes — they funnel through this function since F-362.
  check(
    "writeModeReport: the report filename carries the run's UTC date, not merely a date-shaped string",
    [utcBefore, utcAfter].includes(basename(a.outPath).replace(/^search-/, "").replace(/\.md$/, "")),
    { basename: basename(a.outPath), utcBefore, utcAfter }
  );
  check("writeModeReport: csvDir = resolved --csv-dir, created; clean run pushes no caveat", a.csvDir === resolve(flags["csv-dir"]) && existsSync(a.csvDir) && cavA.length === 1, { csvDir: a.csvDir, cavA });
  // F-397: the caveats CSV is the shared tail's, so the four modes carry it by
  // construction (tenant-deps-caveats.csv parity, F-388). Parsed back from the
  // bytes the writer emits (BOM + CRLF), never re-rendered through toCsv, so a
  // writer that stops writing rows, writes a header only, or drops the file reds
  // here; the mode suites' set-locks pin the filename per mode. Quoting is
  // exercised on purpose — a comma and a double quote in the caveat text.
  {
    const cavE = ["plain caveat", "a caveat, with a comma", 'a caveat with a "quoted" word'];
    const e = writeModeReport({ mode: "deps", flags: { index: flags.index, report: join(dir, "rep-e"), "csv-dir": join(dir, "csv-e") }, modeArgs: ["--object Company"], sections: [], caveats: cavE, index });
    const csvPath = join(e.csvDir, "deps-caveats.csv");
    const raw = existsSync(csvPath) ? readFileSync(csvPath, "utf8") : "";
    const lines = raw.replace(/^\uFEFF/, "").split("\r\n").filter((l) => l.length);
    const unq = (l) => (l.startsWith('"') ? l.slice(1, -1).replace(/""/g, '"') : l);
    check(
      "writeModeReport: <mode>-caveats.csv under --csv-dir — BOM, CRLF, `caveat` header, then every caveat as one row in order, comma and quote round-tripped (F-397)",
      raw.startsWith("\uFEFF") && lines[0] === "caveat" && lines.length === cavE.length + 1 && lines.slice(1).map(unq).join("\n") === cavE.join("\n"),
      { raw: raw.slice(0, 200), lines }
    );
    // Header-only when there is nothing to say: the file's presence is unconditional.
    const cavF = [];
    const f = writeModeReport({ mode: "program", flags: { index: flags.index, report: join(dir, "rep-f"), "csv-dir": join(dir, "csv-f") }, modeArgs: ["--name x"], sections: [], caveats: cavF, index });
    const rawF = readFileSync(join(f.csvDir, "program-caveats.csv"), "utf8");
    check("writeModeReport: no caveats → program-caveats.csv is written header-only (never absent) (F-397)", rawF === "\uFEFFcaveat\r\n" && cavF.length === 0, JSON.stringify(rawF));
  }

  // (b) the caveat scan reaches SECTIONS with a clean rerun (the unified scan)
  const cavB = [];
  const b = writeModeReport({ mode: "audit-active", flags: { index: flags.index, report: join(dir, "rep-b") }, modeArgs: [], sections: [`hint: \`gs-admin x --id 'O${ESC}Brien'\``], caveats: cavB, index });
  const mdB = readFileSync(b.outPath, "utf8");
  check("writeModeReport: escape in a SECTION only → the POSIX caveat is pushed (rerun clean)", cavB.length === 1 && /bash apostrophe escape/.test(cavB[0]) && !mdB.split("\n").find((l) => l.startsWith("Re-run:")).includes(ESC), { cavB, rerun: mdB.split("\n").find((l) => l.startsWith("Re-run:")) });
  const rerunB = mdB.split("\n").find((l) => l.startsWith("Re-run:"));
  check("writeModeReport: no --csv-dir → csvDir null; the rerun line is exact (no --csv-dir, no dangling separator)", b.csvDir === null && rerunB === `Re-run: \`node ${q(process.argv[1])} audit-active --index ${q(flags.index)} --report ${q(join(dir, "rep-b"))}\``, { b, rerunB });

  // (c) …and CAVEATS already carrying it
  const cavC = [`fetch each with \`--id 'tpl${ESC}x'\``];
  writeModeReport({ mode: "program", flags: { index: flags.index, report: join(dir, "rep-c") }, modeArgs: ["--name x"], sections: [], caveats: cavC, index });
  check("writeModeReport: escape in a CAVEAT only → the POSIX caveat is pushed once, after it", cavC.length === 2 && /bash apostrophe escape/.test(cavC[1]), cavC);

  // (d) write: false — caveat still counted, nothing written, no directory
  const cavD = [];
  const repD = join(dir, "rep-d");
  const d = writeModeReport({ mode: "program", flags: { index: flags.index, report: repD, "csv-dir": join(dir, "csv-d") }, modeArgs: ["--name nope"], sections: [`hint 'a${ESC}b'`], caveats: cavD, index, write: false });
  check("writeModeReport: write:false → nulls, caveat still pushed, no report dir, no csv dir", d.outPath === null && d.csvDir === null && cavD.length === 1 && !existsSync(repD) && !existsSync(join(dir, "csv-d")), { d, cavD, repD: existsSync(repD) });

  // (e) an apostrophe in a flag VALUE is quoted with the escape and draws the caveat via the rerun line
  const cavE = [];
  const e = writeModeReport({ mode: "deps", flags: { index: flags.index, report: join(dir, "rep'e") }, modeArgs: [], sections: [], caveats: cavE, index });
  const rerunE = readFileSync(e.outPath, "utf8").split("\n").find((l) => l.startsWith("Re-run:"));
  check("writeModeReport: apostrophe in --report → rerun carries the escape and the caveat is pushed (F-123)", rerunE.includes(`rep${ESC}e'`) && cavE.length === 1, { rerunE, cavE });
}

// dispatcher: unknown mode → usage error
{
  const bad = spawnSync(process.execPath, [JO_REPORT, "bogus"], { encoding: "utf8" });
  check("dispatcher: unknown mode exits 1 with usage", bad.status === 1 && /usage/.test(bad.stderr), { status: bad.status, stderr: bad.stderr });
  const noFlags = spawnSync(process.execPath, [JO_REPORT, "index"], { encoding: "utf8" });
  check("dispatcher: index without --kb/--out exits 1 with usage", noFlags.status === 1 && /usage/.test(noFlags.stderr), { status: noFlags.status, stderr: noFlags.stderr });
}

rmSync(ROOT, { recursive: true, force: true });
console.log(failures ? `\n${failures} failure(s)` : "\nAll jo-report checks passed");
process.exit(failures ? 1 : 0);
