#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// relationships-build.mjs (test) — fixtures for scripts/relationships-build.mjs
//
// Covers: the arg/manifest gates; the happy path over a fictional acme KB
// (byte-for-byte against committed expected maps — coverage headers, field
// population, chain order, SET_SCOREV2 GSID resolution incl. the JSON-map
// form, rule→CTA, the unknown-actionType and unrecognized-REST_API-area
// reports, and the dangling-measure-ref flag all demonstrated); the
// program-to-template map (edge extracted from a COMPACTED program doc —
// written by doc-lib's renderProgramDoc, proving compaction preserves the
// reference — and from a raw doc; a program with no refs; an unparseable doc
// reported in the coverage header; a journey stub filtered by depth, not
// mistaken for "parsed, no refs"); determinism (second run byte-identical);
// and the coverage-honesty paths (rules domain all metadata stubs → "pending
// deep ingest" note; partially ingested → partial-coverage warning;
// all-failed domain → no-full-docs note, never "metadata stubs"; no parseable
// scorecard docs → unresolved refs labeled a coverage gap, not tenant
// hygiene; journey domain all stubs → program map carries the pending note).
// Fixtures live under the OS temp dir — no real state, all data fictional
// (acme).
//
// Run:  node plugins/gs-superadmin/test/relationships-build.mjs
// Zero dependencies — Node built-ins only.
// ─────────────────────────────────────────────────────────────────────────────
import { mkdirSync, rmSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const SCRIPTS = join(HERE, "..", "scripts");
const BUILD = join(SCRIPTS, "relationships-build.mjs");
const MANIFEST = join(SCRIPTS, "manifest.mjs");
// The compacted-program-doc fixture is written by the real renderer, so this
// suite proves compaction preserves the template reference end-to-end.
const { renderProgramDoc } = await import(new URL("../scripts/doc-lib.mjs", import.meta.url).href);
const EXPECTED = join(HERE, "fixtures", "relationships-build");
const ROOT = join(tmpdir(), `gs-superadmin-relationships-${process.pid}`);
rmSync(ROOT, { recursive: true, force: true });
mkdirSync(ROOT, { recursive: true });

let failures = 0;
function check(label, cond, detail) {
  console.log(`${cond ? "PASS" : "FAIL"}  ${label}`);
  if (!cond) {
    failures++;
    console.log(`      ${JSON.stringify(detail)}`);
  }
}

function run(args) {
  const res = spawnSync(process.execPath, [BUILD, ...args], { encoding: "utf8" });
  let json = null;
  try { json = JSON.parse(res.stdout); } catch { /* failure path */ }
  return { code: res.status, json, stderr: res.stderr.trim() };
}
function manifest(M, verb, args) {
  const res = spawnSync(process.execPath, [MANIFEST, verb, "--manifest", M, ...args], { encoding: "utf8" });
  if (res.status !== 0) throw new Error(`manifest ${verb} failed: ${res.stderr}`);
  return JSON.parse(res.stdout);
}

// ── Fictional acme KB doc builders (describe-batch doc shape) ────────────────
function doc(key, id, name, payload) {
  return [
    `# ${name}`,
    "",
    "> Full describe doc — generated by describe-batch.mjs, captured 2026-01-15T00:00:00.000Z.",
    "",
    `- key: ${key}`,
    `- id: ${id}`,
    `- name: ${name}`,
    "",
    "```json",
    JSON.stringify(payload, null, 2),
    "```",
    "",
  ].join("\n");
}
const fm = (actionType, areaName, extra) => ({
  actionType,
  areaName,
  srcObject: null,
  srcField: null,
  srcType: "STRING",
  tgtObject: null,
  tgtField: null,
  tgtType: "STRING",
  identifier: false,
  ...extra,
});
const rulePayload = (ruleName, active, maps) => ({ data: { ruleDetails: { ruleName, active, _flatMappings: maps } } });

const RULES = [
  {
    id: "rule-acme-0001",
    name: "CS|Health|Compute Score Trend",
    payload: rulePayload("CS|Health|Compute Score Trend", true, [
      fm("DATA_SYNC", "loadToCompany", { srcObject: "acme_usage_rollup", srcField: "avg_logins_30d", tgtObject: "Company", tgtField: "Health Score Trend" }),
      fm("DATA_SYNC", "mda", { srcObject: "acme_usage_rollup", srcField: "trend_bucket", tgtObject: "acme_health_summary", tgtField: "trend_bucket" }),
      fm("SET_SCOREV2", "scorecardV2", { srcField: "sc-gsid-acme-0001", tgtObject: "scorecard", tgtField: "scorecard" }),
      fm("SET_SCOREV2", "scorecardV2", { srcField: "m-gsid-acme-0101", tgtObject: "scorecard", tgtField: "measure" }),
      fm("SET_SCOREV2", "scorecardV2", { srcField: "Scored nightly by rule", tgtObject: "scorecard", tgtField: "comment" }),
    ]),
  },
  {
    id: "rule-acme-0002",
    name: "CS|Risk|Create Renewal CTA",
    payload: rulePayload("CS|Risk|Create Renewal CTA", false, [
      fm("BULK_API", "loadToSurvey", { srcObject: "acme_nps_batch", srcField: "nps_bucket", tgtObject: "Survey", tgtField: "NPS Bucket" }),
      fm("REST_API", "NativeCta", { srcField: "Renewal risk review", tgtObject: "Call To Action", tgtField: "Name" }),
      fm("REST_API", "NativeCta", { srcField: "High", tgtObject: "Call To Action", tgtField: "Priority" }),
      fm("REST_API", "NativeEmailBlast", { srcField: "renewal_template", tgtObject: "Email", tgtField: "Template" }),
      fm("CONDITIONAL", "scorecardV2", { srcField: "trend_bucket", tgtField: "condition" }),
    ]),
  },
  {
    id: "rule-acme-0003",
    name: "CS|Ops|Sync Legacy Flags",
    payload: rulePayload("CS|Ops|Sync Legacy Flags", true, [
      fm("FLAG_SYNC_V9", "legacyFlags", { srcObject: "acme_flags", srcField: "flag_a", tgtObject: "Company", tgtField: "Legacy Flag A" }),
      fm("FLAG_SYNC_V9", "legacyFlags", { srcObject: "acme_flags", srcField: "flag_b", tgtObject: "Company", tgtField: "Legacy Flag B" }),
      fm("SET_SCOREV2", "scorecardV2", { srcField: "sc-gsid-acme-0001", tgtObject: "scorecard", tgtField: "scorecard" }),
      fm("SET_SCOREV2", "scorecardV2", { srcField: '{"sc-gsid-acme-0001":"m-gsid-acme-0102"}', tgtObject: "scorecard", tgtField: "score" }),
      fm("SET_SCOREV2", "scorecardV2", { srcField: "m-gsid-acme-9999", tgtObject: "scorecard", tgtField: "measure" }),
    ]),
  },
];
// SCORECARD (a card doc: id/name/payload) and CHAIN live in the shared reader
// payload corpus (test/fixtures/reader-payloads.mjs) — the tracer measures the
// same bytes this suite writes into its KB.
import { SCORECARD_CARD as SCORECARD, CHAIN } from "./fixtures/reader-payloads.mjs";
const TEMPLATE_ROWS = [
  { templateId: "tpl-gsid-acme-0001", title: "Welcome Sequence Email" },
  { templateId: "tpl-gsid-acme-0002", title: "Renewal Reminder Email" },
];
const programPayload = (id, name, status, step) => ({
  data: { programId: id, name, status, stepJson: JSON.stringify(step) },
});
// prog 1: doc written COMPACTED (renderProgramDoc); references template 0001.
// prog 2: raw describe-batch-shaped doc; references template 0002.
// prog 3: raw doc, no template references.
// prog 4: unparseable payload (corrupt fence) — reported, never skipped silently.
const PROGRAMS = [
  {
    id: "prog-acme-0001", name: "Acme Onboarding Journey", compact: true,
    payload: programPayload("prog-acme-0001", "Acme Onboarding Journey", "ACTIVE", {
      nodes: [
        { type: "EMAIL", name: "Send welcome", templateId: "tpl-gsid-acme-0001", x: 120, y: 340, style: { color: "#fff" } },
        { type: "WAIT", name: "Wait 3 days", timerValue: 3, intervalUnit: "DAY" },
      ],
      powerListConfig: { sourceType: "CSV", fileName: "acme_participants.csv" },
      viewport: { zoom: 0.8 },
    }),
  },
  {
    id: "prog-acme-0002", name: "Acme Renewal Journey", compact: false,
    payload: programPayload("prog-acme-0002", "Acme Renewal Journey", "ACTIVE", {
      nodes: [{ type: "EMAIL", name: "Renewal nudge", templateId: "tpl-gsid-acme-0002" }],
      powerListConfig: { sourceType: "QUERY" },
    }),
  },
  {
    id: "prog-acme-0003", name: "Acme Churn Watch Journey", compact: false,
    payload: programPayload("prog-acme-0003", "Acme Churn Watch Journey", "DRAFT", {
      nodes: [{ type: "WAIT", name: "Idle", timerValue: 7 }],
      powerListConfig: { sourceType: "DATA_DESIGNER", datasetName: "acme_actives" },
    }),
  },
  { id: "prog-acme-0004", name: "Acme Broken Journey", corrupt: true },
];

// One workspace builder so the scenarios can't drift apart.
// rulesDepth: "full" | "metadata" | ["full", "metadata", …] per index
/**
 * @param {string} slug
 * @param {{rulesDepth?: string|string[], withFailedRule?: boolean, chainsFailed?: boolean,
 *          scorecardDepth?: string, journeyDepth?: string, rules?: any}} [opts]
 */
function buildWorkspace(slug, { rulesDepth = "full", withFailedRule = true, chainsFailed = false, scorecardDepth = "full", journeyDepth = "full", rules = RULES } = {}) {
  const M = join(ROOT, slug, "_manifest.json");
  manifest(M, "init", ["--slug", slug, "--base-url", "https://acme--sbx.gainsightcloud.com", "--environment", "sandbox"]);
  let itemsN = 0;
  const items = (rows) => {
    const p = join(ROOT, `${slug}-items-${++itemsN}.json`);
    writeFileSync(p, JSON.stringify({ data: rows }));
    return p;
  };
  const ruleRows = rules.map((r) => ({ ruleId: r.id, name: r.name }));
  if (withFailedRule) ruleRows.push({ ruleId: "rule-acme-0004", name: "CS|Tmp|Broken Rule" });
  manifest(M, "upsert-batch", ["--file", items(ruleRows), "--domain", "rules-engine", "--id-field", "ruleId", "--name-field", "name"]);
  manifest(M, "upsert-batch", ["--file", items([{ workflowId: CHAIN.id, name: CHAIN.name }]), "--domain", "rules-engine-chains", "--id-field", "workflowId", "--name-field", "name"]);
  manifest(M, "upsert-batch", ["--file", items([{ scorecardId: SCORECARD.id, name: SCORECARD.name }]), "--domain", "scorecard", "--id-field", "scorecardId", "--name-field", "name"]);

  const rulesDir = join(ROOT, slug, "rules-engine");
  mkdirSync(rulesDir, { recursive: true });
  rules.forEach((r, i) => {
    const depth = Array.isArray(rulesDepth) ? rulesDepth[i] : rulesDepth;
    if (depth === "full") writeFileSync(join(rulesDir, `${r.id}.md`), doc(`rules-engine/${r.id}`, r.id, r.name, r.payload));
    // metadata stubs carry no describe payload — an empty stub file stands in
    else writeFileSync(join(rulesDir, `${r.id}.md`), `# ${r.name}\n\n> Metadata-only stub.\n\n- key: rules-engine/${r.id}\n- id: ${r.id}\n- name: ${r.name}\n`);
    manifest(M, "mark", ["--key", `rules-engine/${r.id}`, "--status", "documented", "--depth", depth]);
  });
  if (withFailedRule) manifest(M, "mark", ["--key", "rules-engine/rule-acme-0004", "--status", "failed", "--error", "simulated describe failure"]);

  const chainsDir = join(ROOT, slug, "rules-engine-chains");
  mkdirSync(chainsDir, { recursive: true });
  if (chainsFailed) {
    manifest(M, "mark", ["--key", `rules-engine-chains/${CHAIN.id}`, "--status", "failed", "--error", "simulated describe failure"]);
  } else {
    writeFileSync(join(chainsDir, `${CHAIN.id}.md`), doc(`rules-engine-chains/${CHAIN.id}`, CHAIN.id, CHAIN.name, CHAIN.payload));
    manifest(M, "mark", ["--key", `rules-engine-chains/${CHAIN.id}`, "--status", "documented", "--depth", "full"]);
  }

  const scDir = join(ROOT, slug, "scorecard");
  mkdirSync(scDir, { recursive: true });
  if (scorecardDepth === "full") {
    // The `- id:` bullet is written backtick-QUOTED here on purpose (F-341):
    // four domains' KB docs quote it that way, and the committed expected
    // maps below must stay byte-identical — the scorecard-name registry keys
    // on this id, so a reader that stopped unwrapping the span would render
    // every scorecard hint unresolved and fail the byte-for-byte pins.
    writeFileSync(join(scDir, `${SCORECARD.id}.md`), doc(`scorecard/${SCORECARD.id}`, `\`${SCORECARD.id}\``, SCORECARD.name, SCORECARD.payload));
  } else {
    writeFileSync(join(scDir, `${SCORECARD.id}.md`), `# ${SCORECARD.name}\n\n> Metadata-only stub.\n\n- key: scorecard/${SCORECARD.id}\n- id: ${SCORECARD.id}\n- name: ${SCORECARD.name}\n`);
  }
  manifest(M, "mark", ["--key", `scorecard/${SCORECARD.id}`, "--status", "documented", "--depth", scorecardDepth]);

  // journey programs + email-template inventory (program-to-template map).
  // Template entries stay pending on purpose: the map matches inventory ids
  // at any depth — an id needs no doc to identify an edge.
  manifest(M, "upsert-batch", ["--file", items(TEMPLATE_ROWS), "--domain", "journey-email-templates", "--id-field", "templateId", "--name-field", "title"]);
  manifest(M, "upsert-batch", ["--file", items(PROGRAMS.map((p) => ({ programId: p.id, name: p.name }))), "--domain", "journey", "--id-field", "programId", "--name-field", "name"]);
  const joDir = join(ROOT, slug, "journey");
  mkdirSync(joDir, { recursive: true });
  for (const p of PROGRAMS) {
    if (journeyDepth !== "full") {
      // The key bullet is backtick-QUOTED here on purpose (gate-3 F-353): the
      // journey lane used to read it with a raw regex instead of topBullets,
      // so a quoted key missed the inventory lookup, the depth gate was
      // skipped, and this stub was walked as a full program.
      writeFileSync(join(joDir, `${p.id}.md`), `# ${p.name}\n\n> Metadata-only stub.\n\n- key: \`journey/${p.id}\`\n- id: ${p.id}\n- name: ${p.name}\n\n\`\`\`json\n${JSON.stringify({ programId: p.id, name: p.name })}\n\`\`\`\n`);
      manifest(M, "mark", ["--key", `journey/${p.id}`, "--status", "documented", "--depth", "metadata"]);
      continue;
    }
    if (p.corrupt) writeFileSync(join(joDir, `${p.id}.md`), `# ${p.name}\n\n- key: journey/${p.id}\n- id: ${p.id}\n- name: ${p.name}\n\n\`\`\`json\n{ corrupt\n\`\`\`\n`);
    else if (p.compact) writeFileSync(join(joDir, `${p.id}.md`), renderProgramDoc(p.payload, { key: `journey/${p.id}` }).doc);
    else writeFileSync(join(joDir, `${p.id}.md`), doc(`journey/${p.id}`, p.id, p.name, p.payload));
    manifest(M, "mark", ["--key", `journey/${p.id}`, "--status", "documented", "--depth", "full"]);
  }
  return M;
}

// ── Gates ────────────────────────────────────────────────────────────────────
let r = run([]);
check("gate: missing required args refused", r.code === 1 && /required/.test(r.stderr), r);
r = run(["--manifest", join(ROOT, "nope", "_manifest.json"), "--out-dir", join(ROOT, "nope", "relationships")]);
check("gate: unreadable manifest refused", r.code === 1 && /cannot read manifest/.test(r.stderr), r);
// F-205: a valued flag as the last token has lost its value — refused loudly.
// The setup skill tells the model to APPEND --<x>-domain flags to this fence
// when tenant domain names differ from the defaults, so the old silent
// fallback built the maps against the DEFAULT domain at exit 0 — wrong or
// empty maps. Same rule for --date, which silently stamped today.
r = run(["--manifest", join(ROOT, "nope", "_manifest.json"), "--out-dir", join(ROOT, "nope", "relationships"), "--rules-domain"]);
check("gate: trailing bare --rules-domain refused (F-205)", r.code === 1 && /--rules-domain requires a value/.test(r.stderr), r);
r = run(["--manifest", join(ROOT, "nope", "_manifest.json"), "--out-dir", join(ROOT, "nope", "relationships"), "--date"]);
check("gate: trailing bare --date refused (F-205)", r.code === 1 && /--date requires a value/.test(r.stderr), r);

// ── Happy path: full acme KB → byte-for-byte expected maps ──────────────────
const M1 = buildWorkspace("acme-sbx");
const OUT1 = join(ROOT, "acme-sbx", "relationships");
r = run(["--manifest", M1, "--out-dir", OUT1, "--date", "2026-01-15"]);
check("run: exit 0 with ok summary and 4 generated files", r.code === 0 && r.json?.ok === true && r.json?.generated?.length === 4, r);
check(
  "run: summary counts — rules parsed, measures resolved, dangling flagged",
  r.json?.rules?.withMappings === 3 && r.json?.scorecards?.measuresResolved === 2 && r.json?.danglingMeasureRefs === 1,
  r.json
);
check(
  "run: summary reports the unknown actionType with its rule",
  r.json?.unknownActionTypes?.FLAG_SYNC_V9?.[0] === "CS|Ops|Sync Legacy Flags",
  r.json?.unknownActionTypes
);
check(
  "run: summary reports the unrecognized REST_API area with its rule",
  r.json?.unexpectedRestApiAreas?.NativeEmailBlast?.[0] === "CS|Risk|Create Renewal CTA _(inactive)_",
  r.json?.unexpectedRestApiAreas
);
check(
  "run: program summary — 3 parsed (stub-free), 2 with refs, 2 edges, 2 template ids",
  r.json?.programs?.parsed === 3 && r.json?.programs?.withRefs === 2 &&
    r.json?.programs?.templateEdges === 2 && r.json?.programs?.templatesKnown === 2,
  r.json?.programs
);
const p2tOut = readFileSync(join(OUT1, "program-to-template.md"), "utf8");
check(
  "run: edge extracted from the COMPACTED program doc (renderProgramDoc output)",
  /\*\*Acme Onboarding Journey\*\* → Welcome Sequence Email \(`tpl-gsid-acme-0001`\)/.test(p2tOut),
  p2tOut.slice(0, 900)
);
check(
  "run: edge extracted from the raw describe-batch-shaped doc too",
  /\*\*Acme Renewal Journey\*\* → Renewal Reminder Email \(`tpl-gsid-acme-0002`\)/.test(p2tOut),
  p2tOut
);
check("run: no-ref program counted, not listed as an edge", /1 of 3 parsed program doc\(s\) reference no documented template/.test(p2tOut) && !/Churn Watch/.test(p2tOut), p2tOut);
check(
  "run: unparseable program doc reported in the coverage header, never skipped silently",
  /journey: 1 full doc\(s\) had no parseable describe payload/.test(p2tOut),
  p2tOut.slice(0, 600)
);
// Deliberate fixture refresh (after a reviewed generator change):
//   RELATIONSHIPS_EXPECTED_REFRESH=1 node plugins/gs-superadmin/test/relationships-build.mjs
//   PowerShell: $env:RELATIONSHIPS_EXPECTED_REFRESH = '1'; node plugins/gs-superadmin/test/relationships-build.mjs
// rewrites the committed expected maps from the current output — review the git
// diff of test/fixtures/relationships-build/ before committing. The inline
// VAR=value prefix is bash-only: PowerShell parses that line and fails at runtime
// on the VAR=value token, so the refresh silently does not happen (F-255).
if (process.env.RELATIONSHIPS_EXPECTED_REFRESH) {
  mkdirSync(EXPECTED, { recursive: true });
  for (const name of ["field-to-rule.md", "field-to-scorecard.md", "process-maps.md", "program-to-template.md"]) {
    writeFileSync(join(EXPECTED, `expected-${name}`), readFileSync(join(OUT1, name), "utf8"));
  }
  console.log("      (expected fixtures refreshed from this run)");
}
// EOL contract (OS-portability wave 5): the generator must emit LF-only bytes
// on every OS — a CR in its output would dirty the CI rebuild-and-diff on the
// Windows leg and churn the committed maps. The fixture compare normalizes
// CRLF→LF on BOTH sides so an out-of-repo checkout (where .gitattributes
// doesn't travel and the expected maps may arrive CRLF) still compares content.
const lfOnly = (s) => s.replace(/\r\n/g, "\n");
for (const name of ["field-to-rule.md", "field-to-scorecard.md", "process-maps.md", "program-to-template.md"]) {
  const got = readFileSync(join(OUT1, name), "utf8");
  const want = readFileSync(join(EXPECTED, `expected-${name}`), "utf8");
  check(`no CR: ${name} generator output is LF-only on this OS`, !got.includes("\r"), got.slice(0, 400));
  check(`byte-for-byte: ${name} matches the committed expected map (EOL-normalized)`, lfOnly(got) === lfOnly(want), got.slice(0, 400));
}

// Determinism: a second run reproduces the exact same bytes.
const first = readFileSync(join(OUT1, "field-to-rule.md"), "utf8");
r = run(["--manifest", M1, "--out-dir", OUT1, "--date", "2026-01-15"]);
check("determinism: re-run is byte-identical", r.code === 0 && readFileSync(join(OUT1, "field-to-rule.md"), "utf8") === first, null);

// ── Coverage degradation: rules domain all metadata stubs ────────────────────
const M2 = buildWorkspace("acme2-sbx", { rulesDepth: "metadata", withFailedRule: false });
const OUT2 = join(ROOT, "acme2-sbx", "relationships");
r = run(["--manifest", M2, "--out-dir", OUT2, "--date", "2026-01-15"]);
const stubbed = readFileSync(join(OUT2, "field-to-rule.md"), "utf8");
check(
  "stubs: rules domain excluded in the coverage header with the --deep command",
  /Excluded \(metadata stubs\): rules-engine — re-run after `\/gs-superadmin:setup --deep rules-engine`/.test(stubbed),
  stubbed.slice(0, 500)
);
check("stubs: pending-deep-ingest note instead of a thin map", /Pending deep ingest/.test(stubbed), stubbed.slice(0, 800));
check(
  "stubs: scorecard map also carries the pending note (rules are its input too)",
  /Pending deep ingest/.test(readFileSync(join(OUT2, "field-to-scorecard.md"), "utf8")),
  null
);

// ── Coverage degradation: partial ingest warns but maps the full docs ────────
const M3 = buildWorkspace("acme3-sbx", { rulesDepth: ["full", "metadata", "metadata"], withFailedRule: false });
const OUT3 = join(ROOT, "acme3-sbx", "relationships");
r = run(["--manifest", M3, "--out-dir", OUT3, "--date", "2026-01-15"]);
const partial = readFileSync(join(OUT3, "field-to-rule.md"), "utf8");
check("partial: header counts full docs (1/3)", /rules-engine \(1\/3 full\)/.test(partial), partial.slice(0, 400));
check("partial: partial-coverage warning names the --deep re-run", /partially ingested[\s\S]*--deep rules-engine/.test(partial), partial.slice(0, 700));
check("partial: map still built from the full doc", /\*\*Health Score Trend\*\* ← CS\|Health\|Compute Score Trend/.test(partial), partial);
check(
  "partial: rules absent from full docs are absent from the map",
  !/Renewal CTA/.test(partial.split("## actionType accounting")[0]),
  null
);

// ── Coverage honesty: all-failed domain is not called "metadata stubs" ───────
const M4 = buildWorkspace("acme4-sbx", { chainsFailed: true, withFailedRule: false });
const OUT4 = join(ROOT, "acme4-sbx", "relationships");
r = run(["--manifest", M4, "--out-dir", OUT4, "--date", "2026-01-15"]);
const failedChains = readFileSync(join(OUT4, "field-to-rule.md"), "utf8");
check(
  "all-failed: domain reported as no-full-docs, not as metadata stubs",
  /rules-engine-chains: no full docs to build from \(1 failed, 0 pending\/stale\)/.test(failedChains) &&
    !/Excluded \(metadata stubs\): rules-engine-chains/.test(failedChains),
  failedChains.slice(0, 600)
);
check("all-failed: no --deep advice for a domain with nothing stubbed", !/--deep rules-engine-chains/.test(failedChains), null);

// ── Coverage honesty: unresolved refs without scorecard docs ≠ tenant hygiene ─
const M5 = buildWorkspace("acme5-sbx", { scorecardDepth: "metadata", withFailedRule: false });
const OUT5 = join(ROOT, "acme5-sbx", "relationships");
r = run(["--manifest", M5, "--out-dir", OUT5, "--date", "2026-01-15"]);
const noSc = readFileSync(join(OUT5, "field-to-scorecard.md"), "utf8");
check(
  "no-scorecards: unresolved refs labeled a coverage gap, not tenant hygiene",
  /Unresolved measure references — no scorecard docs to resolve against/.test(noSc) &&
    /coverage gap, not a tenant-hygiene\s+signal/.test(noSc) &&
    !/tenant-hygiene signal\)/.test(noSc),
  noSc.slice(0, 900)
);
check(
  "no-scorecards: scorecard domain excluded as stubs in the coverage header",
  /Excluded \(metadata stubs\): scorecard — re-run after/.test(noSc),
  noSc.slice(0, 400)
);

// ── process-maps: the journey↔rules architecture note replaces the old gap ──
const pmOut = readFileSync(join(OUT1, "process-maps.md"), "utf8");
check(
  "process-maps: states there is no journey→rule participant edge (Power Lists, never a rule)",
  /no participant edge exists/.test(pmOut) && /Power\s+Lists/.test(pmOut) && /never a rule/.test(pmOut),
  pmOut.slice(-900)
);
check("process-maps: no longer invites hand-built journey→rule synthesis", !/Trace journey→rule chains/.test(pmOut), null);

// ── Coverage honesty: journey domain all stubs → program map pending note ───
const M6 = buildWorkspace("acme6-sbx", { journeyDepth: "metadata", withFailedRule: false });
const OUT6 = join(ROOT, "acme6-sbx", "relationships");
r = run(["--manifest", M6, "--out-dir", OUT6, "--date", "2026-01-15"]);
const p2tStubbed = readFileSync(join(OUT6, "program-to-template.md"), "utf8");
check(
  "journey-stubs: pending-deep-ingest note instead of a thin map",
  /Pending deep ingest — no fully-described journey program docs/.test(p2tStubbed) && /--deep journey/.test(p2tStubbed),
  p2tStubbed.slice(0, 700)
);
check(
  "journey-stubs: stub docs filtered by depth, not counted as parsed-no-refs",
  r.json?.programs?.parsed === 0 && r.json?.programs?.withRefs === 0,
  r.json?.programs
);

// ── CP-5 (CLI 1.0.6 adoption rider): the two 1.0.6 payload shapes ───────────
// Path-scoped delta (see the generator's `_flatMappings` semantics block):
// the 1.0.6 list-and-describe enricher blanks `tgtObject` on external-action
// (callExternalAPI) and task-id (`t1`-style) rows, while the per-item
// describe path still emits the old unfiltered values. Scenario 1 pins the
// blanked shape: blank rows drop out of the write index while real mappings
// on the same rule still index and callExternalAPI stays recognized-and-
// counted. Scenario 2 is the committed negative control — the raw
// describe-path shape, whose `t1` target DOES mint a (bogus) write-index
// bucket; if a future generator change starts filtering raw task-id values,
// this assertion is the tripwire that says the semantics block needs
// re-scoping again.
const RULE_106 = {
  id: "rule-acme-0106",
  name: "CS|Ops|Push Usage To External API",
  payload: rulePayload("CS|Ops|Push Usage To External API", true, [
    fm("DATA_SYNC", "loadToCompany", { srcObject: "acme_usage_rollup", srcField: "avg_logins_30d", tgtObject: "Company", tgtField: "Health Score Trend" }),
    // list-and-describe path, 1.0.6: blanked callout-parameter target…
    fm("REST_API", "callExternalAPI", { srcObject: "acme_usage_rollup", srcField: "account_ref", tgtObject: "", tgtField: "account_id" }),
    // …and blanked task-id target (raw shape covered by scenario 2).
    fm("DATA_SYNC", "mda", { srcObject: "acme_usage_rollup", srcField: "next_step", tgtObject: "", tgtField: "next_step_col" }),
  ]),
};
const M7 = buildWorkspace("acme7-sbx", { withFailedRule: false, rules: [RULE_106] });
const OUT7 = join(ROOT, "acme7-sbx", "relationships");
r = run(["--manifest", M7, "--out-dir", OUT7, "--date", "2026-01-15"]);
const f2r106 = readFileSync(join(OUT7, "field-to-rule.md"), "utf8");
const f2r106Map = f2r106.split("## actionType accounting")[0];
const f2r106Accounting = f2r106.split("## actionType accounting")[1] ?? "";
check(
  "cli-1.0.6 blanked shape: real mapping on the same rule still indexed",
  r.code === 0 && /\*\*Health Score Trend\*\* ← CS\|Ops\|Push Usage To External API/.test(f2r106Map),
  f2r106.slice(0, 900)
);
check(
  "cli-1.0.6 blanked shape: blank DATA_SYNC target mints no edge and no bogus object",
  !/next_step_col/.test(f2r106Map) && !/\bt\d+\b/.test(f2r106Map),
  f2r106Map
);
// NOTE deliberately absent: a "blank REST_API target mints no edge" check
// would be vacuous — REST_API rows never enter the write index on any path
// (review gate F-098). The REST_API row's pin is the accounting line below.
check(
  "cli-1.0.6 blanked shape: all three rows counted in the accounting (DATA_SYNC 2, REST_API 1)",
  /DATA_SYNC[^\n]*2/.test(f2r106Accounting) && /REST_API[^\n]*1/.test(f2r106Accounting),
  f2r106Accounting.slice(0, 600)
);
check(
  "cli-1.0.6 blanked shape: callExternalAPI recognized-and-counted, nothing unknown/unexpected",
  r.code === 0 && Object.keys(r.json?.unknownActionTypes ?? {}).length === 0 && Object.keys(r.json?.unexpectedRestApiAreas ?? {}).length === 0,
  r.json
);

// Scenario 2 — negative control: the raw per-item-describe shape at 1.0.6.
const RULE_RAW = {
  id: "rule-acme-0107",
  name: "CS|Ops|Legacy Describe Shape",
  payload: rulePayload("CS|Ops|Legacy Describe Shape", true, [
    fm("DATA_SYNC", "mda", { srcObject: "acme_usage_rollup", srcField: "next_step", tgtObject: "t1", tgtField: "next_step_col" }),
  ]),
};
const M8 = buildWorkspace("acme8-sbx", { withFailedRule: false, rules: [RULE_RAW] });
const OUT8 = join(ROOT, "acme8-sbx", "relationships");
r = run(["--manifest", M8, "--out-dir", OUT8, "--date", "2026-01-15"]);
const f2rRawMap = readFileSync(join(OUT8, "field-to-rule.md"), "utf8").split("## actionType accounting")[0];
check(
  "raw describe shape (negative control): task-id target DOES mint the bogus t1 bucket",
  r.code === 0 && /\bt1\b/.test(f2rRawMap) && /next_step_col/.test(f2rRawMap),
  f2rRawMap
);

// ── F-429 second pass: a RENAMED journey domain end to end (the builder's
// blind spot (1) at hb-20260908-01). The workspace records its programs list
// under `jo-programs-x`; with no --journey-domain flag the builder reads that
// folder, the JSON summary says which folder and why (domainDirs /
// domainDirBasis, consumer-parity with tenant-deps), and the resolver's
// warning rides every map's coverage header — the markdown a reader opens.
{
  const M9 = buildWorkspace("acme9-sbx", { withFailedRule: false });
  const slugDir = join(ROOT, "acme9-sbx");
  const rows = join(ROOT, "acme9-programs.json");
  const PARSEABLE = PROGRAMS.filter((p) => p.payload); // the corrupt fixture program has no payload to render
  writeFileSync(rows, JSON.stringify({ data: PARSEABLE.map((p) => ({ programId: p.id, name: p.name })) }));
  manifest(M9, "upsert-batch", ["--file", rows, "--domain", "jo-programs-x", "--id-field", "programId", "--name-field", "name", "--no-date-field", "--list-command", "gs-admin --json jo p list"]);
  mkdirSync(join(slugDir, "jo-programs-x"), { recursive: true });
  for (const p of PARSEABLE) {
    writeFileSync(join(slugDir, "jo-programs-x", `${p.id}.md`), doc(`jo-programs-x/${p.id}`, p.id, p.name, p.payload));
    manifest(M9, "mark", ["--key", `jo-programs-x/${p.id}`, "--status", "documented", "--depth", "full"]);
  }
  const OUT9 = join(slugDir, "relationships");
  r = run(["--manifest", M9, "--out-dir", OUT9, "--date", "2026-01-15"]);
  const MOVED = "KB folders resolved from the manifest's recordings, differing from the defaults: journey → jo-programs-x (default journey)";
  check(
    "F-429 renamed journey: with no --journey-domain flag the builder reads the RECORDED folder and the summary says so (domainDirs / domainDirBasis / warnings)",
    r.code === 0 && r.json?.domainDirs?.journey === "jo-programs-x" && r.json?.domainDirBasis?.journey === "manifest recording" && r.json?.domainDirs?.rules === "rules-engine" && r.json?.domainDirBasis?.rules === "default (no recording)" &&
      r.json?.programs?.parsed === PARSEABLE.length && (r.json?.warnings ?? []).includes(MOVED),
    { code: r.code, dirs: r.json?.domainDirs, basis: r.json?.domainDirBasis, programs: r.json?.programs, warnings: r.json?.warnings, stderr: r.stderr.slice(0, 300) }
  );
  const p2t9 = readFileSync(join(OUT9, "program-to-template.md"), "utf8");
  const f2r9 = readFileSync(join(OUT9, "field-to-rule.md"), "utf8");
  check(
    "F-429 renamed journey parity: the resolver's warning is in EVERY map's coverage header (program-to-template and field-to-rule read here), not only the JSON",
    p2t9.includes(`> ${MOVED}.`) && f2r9.includes(`> ${MOVED}.`) && p2t9.includes("Built from full docs of: jo-programs-x (3/3 full)"),
    { p2tHead: p2t9.slice(0, 700) }
  );
  r = run(["--manifest", M9, "--out-dir", join(slugDir, "relationships-forced"), "--date", "2026-01-15", "--journey-domain", "journey"]);
  check(
    "F-429 renamed journey: an explicit --journey-domain still wins, and the basis names the flag",
    r.code === 0 && r.json?.domainDirs?.journey === "journey" && r.json?.domainDirBasis?.journey === "flag --journey-domain",
    { dirs: r.json?.domainDirs, basis: r.json?.domainDirBasis }
  );
  // F-434 (release-gate review of 0.37.0): the flag goes INTO the resolver, so
  // the "resolved from the recordings" warning does not appear on any surface
  // for a lane the flag overrode — the map header and the JSON agree.
  const p2tForced = readFileSync(join(slugDir, "relationships-forced", "program-to-template.md"), "utf8");
  check(
    "F-434: with the flag in force NO map header and no summary warning claims the lane was resolved from the recording",
    !p2tForced.includes(MOVED) && !(r.json?.warnings ?? []).some((w) => w.includes("jo-programs-x")) && p2tForced.includes("Built from full docs of: journey ("),
    { warnings: r.json?.warnings, head: p2tForced.slice(0, 500) }
  );
}

rmSync(ROOT, { recursive: true, force: true });
console.log(failures ? `\n${failures} check(s) failed` : "\nAll relationships-build checks passed");
process.exit(failures ? 1 : 0);
